languageDict = {
'google': {"el": "Greek", "eo": "Esperanto", "en": "English", "af": "Afrikaans", "sw": "Swahili", "ca": "Catalan", "it": "Italian", "iw": "Hebrew", "sv": "Swedish", "cs": "Czech", "cy": "Welsh", "ar": "Arabic", "ur": "Urdu", "ga": "Irish", "eu": "Basque", "et": "Estonian", "az": "Azerbaijani", "id": "Indonesian", "es": "Spanish", "ru": "Russian", "gl": "Galician", "nl": "Dutch", "pt": "Portuguese", "la": "Latin", "tr": "Turkish", "tl": "Filipino", "lv": "Latvian", "lt": "Lithuanian", "th": "Thai", "vi": "Vietnamese", "gu": "Gujarati", "ro": "Romanian", "is": "Icelandic", "pl": "Polish", "ta": "Tamil", "yi": "Yiddish", "be": "Belarusian", "fr": "French", "bg": "Bulgarian", "uk": "Ukrainian", "hr": "Croatian", "bn": "Bengali", "sl": "Slovenian", "ht": "Haitian Creole", "da": "Danish", "fa": "Persian", "hi": "Hindi", "fi": "Finnish", "hu": "Hungarian", "ja": "Japanese", "ka": "Georgian", "te": "Telugu", "zh-TW": "Chinese Traditional", "sq": "Albanian", "no": "Norwegian", "ko": "Korean", "kn": "Kannada", "mk": "Macedonian", "zh-CN": "Chinese Simplified", "sk": "Slovak", "mt": "Maltese", "de": "German", "ms": "Malay", "sr": "Serbian", "auto": "Auto"},

'baidu': {"el": "\u5e0c\u814a\u8bed", "en": "\u82f1\u8bed", "zh": "\u4e2d\u6587", "rom": "\u7f57\u9a6c\u5c3c\u4e9a\u8bed", "it": "\u610f\u5927\u5229\u8bed", "ara": "\u963f\u62c9\u4f2f\u8bed", "cs": "\u6377\u514b\u8bed", "spa": "\u897f\u73ed\u7259\u8bed", "ru": "\u4fc4\u8bed", "fra": "\u6cd5\u8bed", "est": "\u7231\u6c99\u5c3c\u4e9a\u8bed", "nl": "\u8377\u5170\u8bed", "pt": "\u8461\u8404\u7259\u8bed", "swe": "\u745e\u5178\u8bed", "cht": "\u7e41\u4f53\u4e2d\u6587", "th": "\u6cf0\u8bed", "kor": "\u97e9\u8bed", "fin": "\u82ac\u5170\u8bed", "pl": "\u6ce2\u5170\u8bed", "auto": "\u81ea\u52a8\u68c0\u6d4b", "dan": "\u4e39\u9ea6\u8bed", "de": "\u5fb7\u8bed", "jp": "\u65e5\u8bed", "hu": "\u5308\u7259\u5229\u8bed", "bul": "\u4fdd\u52a0\u5229\u4e9a\u8bed", "wyw": "\u6587\u8a00\u6587", "slo": "\u65af\u6d1b\u6587\u5c3c\u4e9a\u8bed", "yue": "\u7ca4\u8bed"},

'iciba': {"fr": "\u6cd5\u8bed", "en": "\u82f1\u6587", "zh": "\u4e2d\u6587", "de": "\u5fb7\u8bed", "ko": "\u97e9\u8bed", "ja": "\u65e5\u8bed", "es": "\u897f\u73ed\u7259\u8bed", "auto": "Auto"},

'youdao': {"ru": "\u4fc4\u8bed", "fr": "\u6cd5\u8bed", "en": "\u82f1\u6587", "kr": "\u97e9\u8bed", "sp": "\u897f\u73ed\u7259\u8bed", "zh-CN": "\u4e2d\u6587", "ja": "\u65e5\u8bed", "auto": "Auto"},

'bing': {"-": "Auto", "auto": "Auto", "el": "Greek", "zh-CHS": "Chinese Simplified", "zh-CHT": "Chinese Traditional", "af": "Afrikaans", "ko": "Korean", "ca": "Catalan", "it": "Italian", "cy": "Welsh", "ar": "Arabic", "otq": "Quer\u00e9taro Otomi", "cs": "Czech", "et": "Estonian", "id": "Indonesian", "es": "Spanish", "ru": "Russian", "mww": "Hmong Daw", "pt": "Portuguese", "no": "Norwegian", "tr": "Turkish", "lv": "Latvian", "lt": "Lithuanian", "en": "English", "th": "Thai", "vi": "Vietnamese", "ro": "Romanian", "pl": "Polish", "fr": "French", "bg": "Bulgarian", "uk": "Ukrainian", "hr": "Croatian", "sr-Cyrl": "Serbian (Cyrillic)", "de": "German", "ht": "Haitian Creole", "da": "Danish", "fa": "Persian", "hi": "Hindi", "fi": "Finnish", "hu": "Hungarian", "ja": "Japanese", "he": "Hebrew", "bs-Latn": "Bosnian (Latin)", "tlh": "Klingon", "sw": "Kiswahili", "sv": "Swedish", "ur": "Urdu", "sk": "Slovak", "mt": "Maltese", "tlh-Qaak": "Klingon (pIqaD)", "sr-Latn": "Serbian (Latin)", "ms": "Malay", "sl": "Slovenian", "yua": "Yucatec Maya", "nl": "Dutch"},
}

